viaa:
    logging:
        level: DEBUG
app:
    pulsar:
        host: !ENV ${PULSAR_HOST}
        port: !ENV ${PULSAR_PORT}
    aip-creator:
        consumer_topic: !ENV ${AIP_CONSUMER_TOPIC}
        producer_topic: !ENV ${AIP_PRODUCER_TOPIC}
        pid_url: !ENV ${PID_URL}
        aip_folder: !ENV ${AIP_FOLDER}
        host: !ENV ${HOST}
